### ISSUE TITLE
Missing colours in diff

### ISSUE THREAD

**Issue by Beelzenef** [MatiasOlivera/universe-theme#1]
It is difficult to recognize changes in files. This is an example with Markdown, but it also happens with other languages.

![Markdown changes](https://user-images.githubusercontent.com/6389665/55091513-40e9ac00-50b1-11e9-94cc-8cf3491cc8f5.png)

Love the theme btw! ❤️

**Comment by MatiasOlivera** [comment]
Yes, you are right. It's something I must fix. I used blue tones because some background colors like red/green make it really difficult to read the code, especially when the words are pink or purple. Thanks!
