### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by AntJanus** [MatiasOlivera/universe-theme#14]
Hey! I'd love to add Elixir support to the theme as I use Elixir most of the time (when I don't use JS).

From what I can tell, interpolated strings are the only ones that don't display correctly 
![image](https://user-images.githubusercontent.com/733810/55418006-05c2ff00-552f-11e9-9c4f-320cd086ab51.png)

Here's what the same snippet looks like in Night Owl

![image](https://user-images.githubusercontent.com/733810/55418059-1d01ec80-552f-11e9-9850-a7cfc0428ec6.png)

I can open a PR and handle this if you can point in the right direction! :)

**Comment by AntJanus** [comment]
It took me a bit but here's the definition that colorized those brackets:

```
{ 
       "name": "Punctuation Section Embedded",
	"scope": "punctuation.section.embedded",
	"settings": {
		"foreground": "#d3423e"
	}
}
```

**Comment by MatiasOlivera** [comment]
Thanks for open this issue @AntJanus! As this repo doesn't have documentation about how to add a new language, how to maintain an existing one and the rationale behind each color, I prefer to do this myself, at least until we have that.

**Comment by MatiasOlivera** [comment]
I will open a pull request, you could help me to test the syntax highlight. I need to make sure the colors work well in real-world code examples.

**Comment by AntJanus** [comment]
@MatiasOlivera Awesome! Thanks! :)

**Comment by MatiasOlivera** [comment]
@AntJanus I changed the `brackets` to purple. It is a color that has good contrast with green. What do you think?

![Elixir](https://user-images.githubusercontent.com/16739011/55427338-21dd9500-555d-11e9-80ff-a5a9420be507.png)

**Comment by AntJanus** [comment]
@MatiasOlivera I think that's the best best color in this color scheme. Thanks! :)

**Comment by MatiasOlivera** [comment]
@AntJanus I just release a new patch version (v1.0.1) with the changes that fix this issue.  🎉
