### ISSUE TITLE
Add italic variants

### ISSUE THREAD

**Issue by MatiasOlivera** [MatiasOlivera/universe-theme#3]
### Variants
| Name                 | Background | Text Style |
|----------------------|------------|------------|
| Universe             | Normal     | Normal     |
| Universe italic      | Normal     | _Italic_     |

### Why?
- The italic version is to make it prettier

**Comment by phaux** [comment]
After latest update the default theme is already contrast-y enough IMO. I'm using it daily and it looks great even in sunlight. There's no point in making extra variant with more saturation. 

For visually impaired people there's always default high contrast theme from vscode.

**Comment by MatiasOlivera** [comment]
> I'm using it daily and it looks great even in sunlight.

That's good, it's what I was looking for 😊

> There's no point in making extra variant with more saturation.

It's was an idea from some people who prefer more saturated syntax highlighting. The _italic_ version is the only that I am going to add. I don't want it to have too many variants because it's going to be harder to maintain 😱

Thanks @phaux

**Comment by phaux** [comment]
I was the one on twitter who wanted extra contrast variant but I changed my mind :stuck_out_tongue:

**Comment by andreheringer** [comment]
Hey @MatiasOlivera, are you planing on releasing the italic variant soon? I'm really looking forward to it. Universe is great btw, love it!

**Comment by MatiasOlivera** [comment]
@andreheringer Hi André! Yes, I will do it soon. I do not know exactly when I'll publish it. Thanks!
