### ISSUE TITLE
Question - Reverting to 1.1.0 colour scheme

### ISSUE THREAD

**Issue by shane-smith** [MatiasOlivera/universe-theme#33]
Hello,

After the significant changes in the 1.2.0 update, I'd like to revert back to the appearance found in 1.1.0 (e.g. yellow highlight on currently-selected sidebar panel).

For now, I'm using VS Code's ability to install an older version of an extension:

<img width="520" alt="Screen Shot 2019-04-25 at 10 27 35 am" src="https://user-images.githubusercontent.com/943942/56702736-c742ed80-6744-11e9-81ec-9c8b44d645b0.png">

Although it shows 1.2.0 in the extension list, it's actually 1.1.0 at the moment.

However, In order to continue receiving other updates, I'm wondering if it would be possible to make the primary/secondary/tertiary colours configurable. That way, I can define the colour scheme that I'd like to continue using (1.1.0), without having to remain on that version.

**Comment by MatiasOlivera** [comment]
Hello!

You can revert the changes made in the v1.2, using the `workbench.colorCustomizations` user setting. It allows you to customize your active color theme, here are the steps to override the v1.2 appearance with the v1.1

1. Select the last version of Universe
2. Go to `settings.json`
3. Add the following config to your file: [Reverting to v1.1](https://gist.github.com/MatiasOlivera/a1047b4856a121ccb34eb6f0b7208b73)
4. That all! 🎉

This way you freeze the user interface appearance but still will get syntax highlighting updates.

It's possible to make configurable some colors, but it's not a priority right now.

I hope I've helped!

**Comment by shane-smith** [comment]
Will try that and get back to you. Thanks!
